// react/src/features/app/views/index.tsx
// React Router DOM
import { useNavigate } from 'react-router-dom'

const AppIndex = () => {
	// Navigation
	const navigate = useNavigate()

	return (
		<div className='card'>
			<h1>Hey, you in Home page</h1>

			<div className='force-center'>
				<button type='button' onClick={() => navigate('/todos')}>
					Go To Todo
				</button>
				<button type='button' onClick={() => navigate('/posts')}>
					Go To Post
				</button>
			</div>
		</div>
	)
}

export { AppIndex }

// vue3/src/features/app/views/index.vue
<template>
	<div class="card">
		<h1>Hey, you in Home page</h1>

		<div class="force-center">
			<button type="button" @click="$router.push({ name: 'todoIndex' })">
				Go To Todo
			</button>
			<button type="button" @click="$router.push({ name: 'postIndex' })">
				Go To Post
			</button>
		</div>
	</div>
</template>
