// react/src/App.tsx
// Assets
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'

// Styles
import './App.css'

// React Router DOM
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom'

// Features
import { AppIndex } from './features/app/views/index'
import { PostIndex } from './features/post/views/index'
import { TodoIndex } from './features/todo/views/index'

const App = () => {
	return (
		<Router>
			<div>
				<a href='https://vitejs.dev' target='_blank'>
					<img src={viteLogo} className='logo' alt='Vite logo' />
				</a>
				<a href='https://react.dev' target='_blank'>
					<img src={reactLogo} className='logo react' alt='React logo' />
				</a>
			</div>

			<Routes>
				<Route path='/' element={<AppIndex />} />
				<Route path='/posts' element={<PostIndex />} />
				<Route path='/todos' element={<TodoIndex />} />
			</Routes>
		</Router>
	)
}

export default App

// vue3/src/App.vue
<template>
	<div>
		<a href="https://vitejs.dev" target="_blank">
			<img src="/vite.svg" class="logo" alt="Vite logo" />
		</a>
		<a href="https://vuejs.org/" target="_blank">
			<img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
		</a>
	</div>
	<router-view />
</template>

<style scoped>
.logo {
	height: 6em;
	padding: 1.5em;
	will-change: filter;
	transition: filter 300ms;
}
.logo:hover {
	filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
	filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
